name: corona_dashboard
description: Corona Dashboard.
version: 0.0.1+1

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^1.0.0+5
  auto_size_text: ^2.1.0
  built_collection: ^4.3.2
  built_value: ^7.0.9
  cupertino_icons: ^0.1.3
  flutter_bloc: ^3.2.0
  http: ^0.12.0+4
  package_info: ^0.4.0+14
  rxdart: ^0.23.1
  time: ^1.2.0
  timeago: ^2.0.26
  tuple: ^1.0.3
  uuid: ^2.0.4
  webview_flutter: ^0.3.19+9

dev_dependencies:
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  pedantic: ^1.9.0
  test: ^1.14.1

flutter:
  uses-material-design: true
